version: "3.9"
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  server:
    build: ./server
    container_name: backend-container
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    restart: on-failure:5

  nginx:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: nginx-container
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
