
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - server_pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: backend-container
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    restart: on-failure:5

  frontend-build:
    build: ./client
    container_name: frontend-build
    command: npm run build
    volumes:
      - frontend-dist:/app/dist

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - frontend-build

volumes:
  server_pgdata:
    external: true
  frontend-dist:
